#
# This is free software, lisence use MIT.
# 

name: Update-packages

on:
  push:
    paths:
      - '.github/workflows/main.yml'
  watch:
    types: started
  repository_dispatch:
  workflow_dispatch:

jobs:
  update:
    runs-on: Ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Set git identity
      run : |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Syn upstream
      run: |
        git rm -r --cache * >/dev/null 2>&1 & rm -rf `find ./* -maxdepth 0 -type d ! -name "diy"` >/dev/null 2>&1
        function git_clone() (
          git clone --depth 1 $1 $2 || true
        )
        function git_sparse_clone() (
          branch="$1" rurl="$2" localdir="$3" && shift 3
          git clone -b $branch --depth 1 --filter=blob:none --sparse $rurl $localdir
          cd $localdir
          git sparse-checkout init --cone
          git sparse-checkout set $@
          mv -n $@ ../
          cd ..
          rm -rf $localdir
          )
        function mvdir() {
        mv -n `find $1/* -maxdepth 0 -type d` ./
        rm -rf $1
        }
        
        svn export https://github.com/vernesong/OpenClash/trunk/luci-app-openclash
        svn export https://github.com/coolsnowwolf/lede/trunk/package/lean/autocore
        
        svn export https://github.com/kiddin9/openwrt-packages/trunk/luci-app-filetransfer
        svn export https://github.com/coolsnowwolf/luci/trunk/libs/luci-lib-fs

    - name: Apply
      run: |
        git add .
        git commit -m "$(date +%Y-%m-%d" "%H:%M:%S)" || true
        git reset --soft HEAD^
        git add .
        git commit -m "$(date +%Y-%m-%d" "%H:%M:%S)" || true
        git push

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 3
        
